# Generated by Django 3.1.5 on 2021-03-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='blog_member',
        ),
    ]
