# Generated by Django 3.1.4 on 2021-02-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
