# Generated by Django 3.1.7 on 2021-03-16 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(choices=[('XXL', 'Extra Extra Large'), ('S', 'Small'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium')], default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=40)),
                ('category_for', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('G', 'Girls'), ('B', 'Boys')], max_length=5)),
                ('category_id', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image1', models.CharField(default='', max_length=1000)),
                ('image2', models.CharField(default='', max_length=1000)),
                ('image3', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('sizes', multiselectfield.db.fields.MultiSelectField(choices=[('XXL', 'Extra Extra Large'), ('S', 'Small'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium')], default='', max_length=12)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='FashionerMain.category')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FashionerMain.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='FashionerMain.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FashionerMain.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
