# Generated by Django 3.1.5 on 2021-03-16 06:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('28', 'S'), ('30', 'M'), ('32', 'L'), ('34', 'XL'), ('36', 'XXL'), ('38', 'XXXL')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('28', 'S'), ('30', 'M'), ('32', 'L'), ('34', 'XL'), ('36', 'XXL'), ('38', 'XXXL')], default='', max_length=17),
        ),
    ]
