# Generated by Django 3.1.4 on 2021-03-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionerMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('OW', 'outwear'), ('SW', 'Sports wear')], max_length=3),
        ),
    ]
