# Generated by Django 3.1.4 on 2021-03-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sports wear'), ('OW', 'outwear')], max_length=3),
        ),
    ]
