# Generated by Django 3.1.4 on 2021-03-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0002_auto_20210303_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'outwear'), ('SW', 'Sports wear'), ('S', 'Shirt')], max_length=3),
        ),
    ]
