# Generated by Django 3.1.5 on 2021-03-16 11:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0002_auto_20210316_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('32', 'L'), ('38', 'XXXL'), ('28', 'S'), ('36', 'XXL'), ('34', 'XL'), ('30', 'M')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('G', 'Girls'), ('B', 'Boys'), ('M', 'Men'), ('W', 'Women')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('32', 'L'), ('38', 'XXXL'), ('28', 'S'), ('36', 'XXL'), ('34', 'XL'), ('30', 'M')], default='', max_length=17),
        ),
    ]
