# Generated by Django 3.1.5 on 2021-03-16 19:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0003_auto_20210316_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('32', 'L'), ('38', 'XXXL'), ('36', 'XXL'), ('28', 'S'), ('30', 'M'), ('34', 'XL')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('B', 'Boys'), ('G', 'Girls')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('32', 'L'), ('38', 'XXXL'), ('36', 'XXL'), ('28', 'S'), ('30', 'M'), ('34', 'XL')], default='', max_length=17),
        ),
    ]
