# Generated by Django 3.1.7 on 2021-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0004_auto_20210303_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'Sports wear'), ('OW', 'outwear'), ('S', 'Shirt')], max_length=3),
        ),
    ]
