# Generated by Django 3.1.5 on 2021-03-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0006_auto_20210303_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
