# Generated by Django 3.1.5 on 2021-03-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FashionerMain', '0007_auto_20210311_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=40)),
                ('category_for', models.CharField(choices=[('M', 'Men'), ('K', 'Kids'), ('W', 'Women')], max_length=5)),
                ('category_id', models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
