# Generated by Django 3.1.5 on 2021-03-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], max_length=5),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image1', models.CharField(default='', max_length=500)),
                ('image2', models.CharField(default='', max_length=500)),
                ('image3', models.CharField(default='', max_length=500)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='FashionerMain.category')),
            ],
        ),
    ]
