# Generated by Django 3.1.5 on 2021-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0012_auto_20210311_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('K', 'Kids')], max_length=5),
        ),
    ]
