# Generated by Django 3.1.5 on 2021-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0013_auto_20210311_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('W', 'Women'), ('K', 'Kids'), ('M', 'Men')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
