# Generated by Django 3.1.5 on 2021-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0015_auto_20210313_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('M', 'Men'), ('K', 'Kids'), ('W', 'Women')], max_length=5),
        ),
    ]
