# Generated by Django 3.1.5 on 2021-03-13 15:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0016_auto_20210313_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Medium'), ('XL', 'Extra Large'), ('L', 'Large'), ('S', 'Small'), ('XXL', 'Extra Extra Large')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('K', 'Kids')], max_length=5),
        ),
    ]
