# Generated by Django 3.1.7 on 2021-03-13 16:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0018_auto_20210313_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Men'), ('W', 'Women')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=12),
        ),
    ]
