# Generated by Django 3.1.5 on 2021-03-14 08:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0020_auto_20210314_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('XL', 'Extra Large'), ('M', 'Medium'), ('S', 'Small'), ('L', 'Large'), ('XXL', 'Extra Extra Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Men'), ('W', 'Women')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'Extra Large'), ('M', 'Medium'), ('S', 'Small'), ('L', 'Large'), ('XXL', 'Extra Extra Large')], default='', max_length=12),
        ),
    ]
