# Generated by Django 3.1.5 on 2021-03-14 10:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0020_auto_20210314_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('XL', 'Extra Large'), ('S', 'Small'), ('M', 'Medium'), ('XXL', 'Extra Extra Large'), ('L', 'Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Men'), ('W', 'Women')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'Extra Large'), ('S', 'Small'), ('M', 'Medium'), ('XXL', 'Extra Extra Large'), ('L', 'Large')], default='', max_length=12),
        ),
    ]
