# Generated by Django 3.1.5 on 2021-03-14 15:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0021_auto_20210314_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('M', 'Medium'), ('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('S', 'Small'), ('L', 'Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('W', 'Women'), ('M', 'Men'), ('K', 'Kids')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Medium'), ('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('S', 'Small'), ('L', 'Large')], default='', max_length=12),
        ),
    ]
