# Generated by Django 3.1.5 on 2021-03-14 15:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0022_auto_20210314_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large'), ('M', 'Medium'), ('XXL', 'Extra Extra Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large'), ('M', 'Medium'), ('XXL', 'Extra Extra Large')], default='', max_length=12),
        ),
    ]
