# Generated by Django 3.1.5 on 2021-03-14 15:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FashionerMain', '0024_auto_20210314_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_for',
            field=models.CharField(choices=[('G', 'Girls'), ('W', 'Women'), ('B', 'Boys'), ('M', 'Men')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XXL', 'Extra Extra Large'), ('XL', 'Extra Large'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=12),
        ),
    ]
