# Generated by Django 3.1.5 on 2021-02-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
